# 配置文件

mysql:
  host: 127.0.0.1
  port: 33060
  db: gvb_db
  user: root
  password: 123456
  log_level: local

logger:
  level: info
  prefix: '[gin_project]'
  director: log
  show_line: true
  log_in_console: true

system:
  host: "0.0.0.0"
  port: 8080
  env: local